### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by JavaZWT** [revolist/revogrid-column-date#22]
Hi, @revolist .
I am trying to use revogrid-column-date with vite&vue3. When running in dev mode, and click the date cell ,I am getting the error:
```text
TypeError: Failed to fetch dynamically imported module: https://y0g9y3-3001.sse.codesandbox.io/node_modules/.vite/deps/duet-date-picker.entry.js 
```
Does anyone know how to fix it?

thanks.

![image](https://user-images.githubusercontent.com/23694794/187621279-0db5cd8b-635c-4505-868a-35f349b020b5.png)

codesandbox: https://codesandbox.io/s/prod-violet-y0g9y3

**Comment by Jyoti-Khatkar** [comment]
@JavaZWT did you get the solution of this problem. i am also facing the same issue in vite vue project on revogrid-column-date.

**Comment by JavaZWT** [comment]
> @JavaZWT @revolist did you get the solution of this problem. i am also facing the same issue in vite vue project on revogrid-column-date. ![image](https://user-images.githubusercontent.com/85393946/217820817-eeddd2b8-e7f0-4aa0-b267-2915e595bdc4.png)

I didn't use this component again，and I use [Element DatePicker](https://element-plus.gitee.io/zh-CN/component/date-picker.html#%E9%80%89%E6%8B%A9%E6%9F%90%E4%B8%80%E5%A4%A9) + [Revolist vue3-datagrid VGridVueTemplate](https://github.com/revolist/vue3-datagrid) to define my own component. And you can define your own date-picker template, too

![截图](https://user-images.githubusercontent.com/23694794/217992992-7114d9df-0e98-40df-8415-08eb2e7a6752.PNG)

**Comment by Jyoti-Khatkar** [comment]
@JavaZWT may you send the code , so that i took some idea .....Also just want to confirm from your idea is it will work for any type of input editor, i mean i have to make a column having dropdown option.

**Comment by JavaZWT** [comment]
> 

I created demo on sandbox, you can refer to it.

https://codesandbox.io/p/sandbox/revogrid-vite-forked-kb8m7t?file=%2Fsrc%2FApp.vue

The important is  column.editor = YourTemplate

**Comment by windxnd** [comment]
@JavaZWT I am also facing a similar issue, do you have any solutions?
![image](https://github.com/revolist/revogrid-column-date/assets/43977449/a2fa16dc-0897-4f4d-8a93-9c429305c336)

**Comment by revolist** [comment]
Should be working in the v4+
Update to the latest version of the date picker
