### ISSUE TITLE
I installed npm i @revolist/revogrid-column-date in angular and it doesn't work correctly it tells me: Error: node_modules/@revolist/revogrid-column-date/dist/editor.d.ts:16:21 - error TS2503: Cannot find namespace 'JSX'. 16 render(h: any): JSX.Element;

### ISSUE THREAD

**Issue by Jenvers** [revolist/revogrid-column-date#26]
import '@duetds/date-picker/dist/duet/themes/default.css';
import './style.css';
import { Edition } from '@revolist/revogrid/dist/types/interfaces';
import { DateConfig } from './type';
export declare class ColumnEditor implements Edition.EditorBase {
    private column;
    private saveCallback;
    private calendar;
    private revoFloat;
    constructor(column: DateConfig, saveCallback: (value: any, preventFocus?: boolean) => void);
    element?: HTMLElement | null;
    editCell?: Edition.EditCell;
    componentDidRender(): void;
    disconnectedCallback(): void;
    private onFloatClick;
    render(h: any): JSX.Element;
}

**Comment by revolist** [comment]
It should work ok with v4+
